security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }
        users_in_database:
            entity:
                class: App\Entity\User
                property: email
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_database
            form_login:
                login_path: page_login
                check_path: page_login
                enable_csrf: true
            logout:
                path: page_logout
                target: page_login
                enable_csrf: true

    role_hierarchy:
        ROLE_SUPER_ADMIN : [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_USER]
        ROLE_USER: []
        ROLE_BANNED: [] 
  
        
    access_control:
        - { path: ^/(login|register|about-us|forgot), roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(?!login|register|about_us|forgot), roles: ROLE_USER}

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 
                time_cost: 3 
                memory_cost: 10 
