controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

banned_page:
    path: /banned
    controller: App\Controller\BannedController::banned
